# -*- coding: utf-8 -*-
"""CSCI218 MLP CODE

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1kCybPfan2_dmZ99s_mniuYSvBS24hTod

CSCI 218 MLP CODE - RIYA
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import time
import os
import zipfile
from scipy.io import arff
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

# data loading
try:
    data, meta = arff.loadarff('Rice_Cammeo_Osmancik.arff')
    df = pd.DataFrame(data)
    df['Class'] = df['Class'].str.decode('utf-8')
except FileNotFoundError:
    print("Error: 'Rice_Cammeo_Osmancik.arff' file not found.")
    exit()

print(f"\nDataset loaded: {df.shape[0]} samples, {df.shape[1]-1} features")
print(df.head())

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder

X = df.drop("Class", axis=1)
y = df["Class"]

le = LabelEncoder()
y = le.fit_transform(y)
class_names = le.classes_

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score
import numpy as np

print("===== TUNING HIDDEN NEURONS =====")

neuron_options = [16, 32, 64, 128]
tuning_results = []

for n in neuron_options:
    model = MLPClassifier(
        hidden_layer_sizes=(n,),
        activation="relu",
        solver="adam",
        max_iter=500,
        random_state=42
    )

    model.fit(X_train, y_train)
    pred = model.predict(X_test)
    acc = accuracy_score(y_test, pred)

    tuning_results.append(acc)
    print(f"Neurons: {n:3d} → Accuracy: {acc:.4f}")

best_neurons = neuron_options[np.argmax(tuning_results)]
print(f"\nBest neuron size: {best_neurons}")

import matplotlib.pyplot as plt
import seaborn as sns
import time
from sklearn.metrics import classification_report, confusion_matrix

print("\n===== FINAL MODEL =====")

final_model = MLPClassifier(
    hidden_layer_sizes=(best_neurons,),
    activation="relu",
    solver="adam",
    max_iter=500,
    random_state=42
)

start = time.time()
final_model.fit(X_train, y_train)
train_time = time.time() - start

start = time.time()
y_pred = final_model.predict(X_test)
pred_time = time.time() - start

accuracy = accuracy_score(y_test, y_pred)

print(f"Accuracy: {accuracy:.4f}")
print(f"Training time: {train_time:.4f} sec")
print(f"Prediction time: {pred_time:.6f} sec")

print("\nClassification Report:")
print(classification_report(y_test, y_pred, target_names=class_names, digits=4))


# 🔹 Confusion Matrix plot
cm = confusion_matrix(y_test, y_pred)

plt.figure(figsize=(6,5))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=class_names,
            yticklabels=class_names)

plt.title("Confusion Matrix – MLP")
plt.xlabel("Predicted")
plt.ylabel("Actual")
plt.tight_layout()
plt.show()


#  Tuning graph
plt.figure()
plt.plot(neuron_options, tuning_results, marker="o")
plt.title("Neuron Size vs Accuracy")
plt.xlabel("Hidden Neurons")
plt.ylabel("Accuracy")
plt.grid(True)
plt.show()

# py -m pip install imbalanced-learn
from imblearn.over_sampling import SMOTE

print("Original TrainVal class counts:")
unique, counts = np.unique(y_train, return_counts=True)
print(dict(zip(unique, counts)))

smote = SMOTE(random_state=42)
X_train_smote, y_train_smote = smote.fit_resample(X_train, y_train)

print("\nSMOTE TrainVal class counts:")
unique_smote, counts_smote = np.unique(y_train_smote, return_counts=True)
print(dict(zip(unique_smote, counts_smote)))

algo_smote = final_model
algo_smote.fit(X_train_smote, y_train_smote)

y_pred_smote = algo_smote.predict(X_test)
acc_smote = accuracy_score(y_test, y_pred_smote)

print("\nSMOTE inclusion")
print("Test Accuracy:", acc_smote)

print("\nClassification Report:")
print(classification_report(y_test, y_pred_smote, digits=4))

# confusion matrix and eval
cm_smote = confusion_matrix(y_test, y_pred_smote)

# heatmapping
plt.figure(figsize=(6, 5))
sns.heatmap(cm_smote, annot=True, fmt='d', cmap="Blues",
            xticklabels=np.unique(y_test), yticklabels=np.unique(y_test))
plt.title(f"Confusion Matrix – MLP")
plt.ylabel('True label')
plt.xlabel('Predicted label')
plt.show()