# -*- coding: utf-8 -*-
"""data distribution.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KdTP44-n-BEEaCCyw7wpBVMk1LGnSaaF
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from scipy.io import arff
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.manifold import TSNE
from sklearn.cluster import KMeans

# data loading
try:
    data, meta = arff.loadarff('Rice_Cammeo_Osmancik.arff')
    df = pd.DataFrame(data)
    df['Class'] = df['Class'].str.decode('utf-8')
except FileNotFoundError:
    print("Error: 'Rice_Cammeo_Osmancik.arff' file not found.")
    exit()

X = df.drop('Class', axis=1)
y = df['Class']
le = LabelEncoder()
y_encoded = le.fit_transform(y)
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# seaborn feature heatmap
plt.figure(figsize=(10, 8))
corr_matrix = df.drop('Class', axis=1).corr()

sns.heatmap(corr_matrix, annot=True, cmap='coolwarm', fmt=".2f", linewidths=0.5)
plt.title('Feature Correlation Heatmap', fontsize=16)
plt.show()

# tsne (note: this takes about a minute)
tsne = TSNE(n_components=2, random_state=42, perplexity=30, max_iter=1000)
X_tsne = tsne.fit_transform(X_scaled)

# kmeans clustering
kmeans = KMeans(n_clusters=2, random_state=42, n_init=10)
kmeans_labels = kmeans.fit_predict(X_scaled)

# dataframe for plots
plot_df = pd.DataFrame(X_tsne, columns=['TSNE 1', 'TSNE 2'])
plot_df['Ground Truth'] = y
plot_df['KMeans Cluster'] = kmeans_labels
fig, axes = plt.subplots(1, 2, figsize=(18, 7))

# tsne plotting by ground truth (left plot)
sns.scatterplot(
    x='TSNE 1', y='TSNE 2',
    hue='Ground Truth',
    data=plot_df,
    palette='viridis',
    ax=axes[0],
    s=60, alpha=0.7
)
axes[0].set_title('t-SNE Visualization (Ground Truth)', fontsize=14)
axes[0].grid(True, linestyle='--', alpha=0.5)

# tsne plotting by kmeans clustering (right plot)
sns.scatterplot(
    x='TSNE 1', y='TSNE 2',
    hue=plot_df['KMeans Cluster'].astype(str),
    data=plot_df,
    palette='deep',
    ax=axes[1],
    s=60, alpha=0.7
)

axes[1].set_title('Visual KMeans (Clustering Result)', fontsize=14)
axes[1].grid(True, linestyle='--', alpha=0.5)

plt.suptitle('Comparison: Actual Rice Varieties vs. Unsupervised KMeans Clustering', fontsize=16)
plt.tight_layout()
plt.show()